# Modify with your compiler!! (i'm using, so i need to use a special version to use openMP)
CC = g++
CFLAGS = -g -O2
SRC = src/main.cpp
BIN = bin/p4
BINDIR = bin/

all:
	$(CC) $(CFLAGS) -o $(BIN) $(SRC)

clean:
	rm -rf $(BINDIR)*
